export const mockEvents = [
    {
        id: 1,
        banner_url: "event1.png",
        titulo: "Natal - Fortaleza",
        descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        data_saida: "2020-10-22",
        data_retorno: "2020-10-22",
        local_concentracao: "Praça J Penha",
        destino: "Natal",
        qtd_vagas: 20,
        ritmo: "Longuinho",
        tipo_evento: "Corporativo",
        info_complementar: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        valor_inscricao: 139.99
    },
    {
        id: 2,
        banner_url: "event2.png",
        titulo: "Corrida Solidária",
        descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        data_saida: "2020-10-22",
        data_retorno: "2020-10-22",
        local_concentracao: "Praça J Penha",
        destino: "Natal",
        qtd_vagas: 20,
        ritmo: "Longuinho",
        tipo_evento: "Corporativo",
        info_complementar: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        valor_inscricao: 139.99
    },
    {
        id: 3,
        banner_url: "event1.png",
        titulo: "Corrida Pe Cicero 1",
        descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        data_saida: "2020-10-22",
        data_retorno: "2020-10-22",
        local_concentracao: "Praça J Penha",
        destino: "Natal",
        qtd_vagas: 20,
        ritmo: "Longuinho",
        tipo_evento: "Corporativo",
        info_complementar: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        valor_inscricao: 139.99
    },
    {
        id: 4,
        banner_url: "event2.png",
        titulo: "Corrida Pe Cicero 2",
        descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        data_saida: "2020-10-22",
        data_retorno: "2020-10-22",
        local_concentracao: "Praça J Penha",
        destino: "Natal",
        qtd_vagas: 20,
        ritmo: "Longuinho",
        tipo_evento: "Corporativo",
        info_complementar: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        valor_inscricao: 139.99
    },

    {
        id: 5,
        banner_url: "event1.png",
        titulo: "Corrida Pe Cicero",
        descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        data_saida: "2020-10-22",
        data_retorno: "2020-10-22",
        local_concentracao: "Praça J Penha",
        destino: "Natal",
        qtd_vagas: 20,
        ritmo: "Longuinho",
        tipo_evento: "Corporativo",
        info_complementar: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        valor_inscricao: 139.99
    },

    {
        id: 6,
        banner_url: "event2.png",
        titulo: "Corrida Pe Cicero 3",
        descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        data_saida: "2020-10-22",
        data_retorno: "2020-10-22",
        local_concentracao: "Praça J Penha",
        destino: "Natal",
        qtd_vagas: 20,
        ritmo: "Longuinho",
        tipo_evento: "Corporativo",
        info_complementar: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        valor_inscricao: 139.99
    },

    {
        id: 7,
        banner_url: "event1.png",
        titulo: "Corrida Pe Cicero 4",
        descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        data_saida: "2020-10-22",
        data_retorno: "2020-10-22",
        local_concentracao: "Praça J Penha",
        destino: "Natal",
        qtd_vagas: 20,
        ritmo: "Longuinho",
        tipo_evento: "Corporativo",
        info_complementar: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        valor_inscricao: 139.99
    }
];